// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: import_of_legacy_library_into_null_safe
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDffTNYULuV7CpylYBh6BVdimlOsOfyJhU',
    appId: '1:971511169859:web:3eaee8b10218abb5f465f6',
    messagingSenderId: '971511169859',
    projectId: 'organizami-7cabd',
    authDomain: 'organizami-7cabd.firebaseapp.com',
    storageBucket: 'organizami-7cabd.appspot.com',
    measurementId: 'G-600LFB28LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwV2NnsOKnlym9usMzyNqFduiY8IckSlE',
    appId: '1:971511169859:android:9eeb0f8d61eb9ea0f465f6',
    messagingSenderId: '971511169859',
    projectId: 'organizami-7cabd',
    storageBucket: 'organizami-7cabd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAhT7Xwn27Khtnkk9Zx6P4AOf98BZ_Cgc',
    appId: '1:971511169859:ios:986295bcf4f02abaf465f6',
    messagingSenderId: '971511169859',
    projectId: 'organizami-7cabd',
    storageBucket: 'organizami-7cabd.appspot.com',
    iosClientId:
        '971511169859-ao35fsd3ejm2j8gfpbkgs9h0jplsgrf2.apps.googleusercontent.com',
    iosBundleId: 'com.example.organizaMi',
  );
}
